apiVersion: demo.chd.com/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: k8s-customization
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
